<a href="https://colab.research.google.com/github/Leerish/Deep-Learning-Notebooks/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fundamental Concepts of TensorFlow

More Specifically , we're going to cover
* Introduction to Tensors
* Getting information from tensors
* Manipulationg Tensors
* Tensors and NumPy
* Using @tf.function
* Using GPU and TPU
* Exercise


## Introduction to Tensors

In [ ]:
# Importing TensorFlow

import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
# Creating Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the dimensions of tensors (ndim - number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10 , 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of vector
vector.ndim

1

In [ ]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10 ,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
matrix2 = tf.constant([[10.0 , 7.1],
                       [3.2 , 2.3],
                       [8.2 , 9.8]] , dtype = tf.float16) # Specify the datatype
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10. ,  7.1],
       [ 3.2,  2.3],
       [ 8.2,  9.8]], dtype=float16)>

In [ ]:
# Whats the number of dimension of matrix2
matrix2.ndim

2

In [ ]:
# Let's Create a Tensor

tensor = tf.constant([[[1 , 2 , 3 ],
                       [3,4,5]],
                      [[4,5,6],
                       [7,8,9]],
                      [[10,11,12],
                       [13,14,15]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

* Scalar : a single number
* Vector: a number with direction( wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers ( n can be any number , 0-dimensional tensor is a scalar , 1-dimensional tensor is a vector)

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Create a tensor using tf.Variable() as above
changeable_tensor = tf. Variable([10, 7])
Unchangeable_tensor = tf.constant([10,7])
changeable_tensor , Unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Changing Elements in changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [ ]:
# Try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Try in unchangeable tensor
Unchangeable_tensor[0].assign(7)

**Note:**Rarely in Practise you need to decide whether to use `tf.constant` or `tf.Variable` to create a tensor , If in doubt use `tf.constant` and change if needed

### Creating random Tensors

Random tensors are tensors of some arbitrary size with random numbers



In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # Set seed
random_1= random_1.normal(shape =(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle a Tensor

* Valuable for when we want to shuffle our data so that the inherent order doesnt affect our learning

In [ ]:
not_shuffled = tf.constant([[10 , 7],
                            [3 ,4],
                            [2,5]])

# Shuffling a tensor
shuffled = tf.random.shuffle(not_shuffled , seed = 42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
# setting random seeds
tf.random.set_seed(42)  #Global level random seed

tf.random.shuffle(not_shuffled , seed = 42) # Operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to create tensors

In [ ]:
# Create a tensor of ones

tf.ones([10 , 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy Arrays into Tensors

The main difference between NumPy arrays and TensorFlow Arrays is that tensors run faster in GPU

In [ ]:
# you can also turn numpy arrays into tensorflow tensors
import numpy as np
arr_1 = np.arange(1 , 25 , dtype=np.int32) # NumPy array between 1 to 25
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# Converting arrays into tensors
a = tf.constant(arr_1)

In [ ]:
a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
a = tf.constant(arr_1 , shape =(2 , 3 ,4))
a

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Inorder to change shape of tensor the new element of shape value should be equal to number of elements in the former array (24 here)

### Getting information from tensors

Attributes of a Tensor
* Shape
* Dimension
* Rank
* Size



In [ ]:
# Create a Rank 4 tensor (4 dimensions)
r4_tensor  = tf.zeros(shape = [ 2 ,3 ,4 ,5])
r4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r4_tensor.shape , r4_tensor.ndim , tf.size(r4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get Various Attributes of tensors
print("Datatype of every element:", r4_tensor.dtype)
print("Number of Dimensions (rank):" ,r4_tensor.ndim)
print("Shape of Tensor:" , r4_tensor.shape)
print("Elements along the 0 axis:" , r4_tensor.shape[0])
print("Elements along the last axis:" , r4_tensor.shape[-1])
print("Total number of elements in our tensor:" , tf.size(r4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of Dimensions (rank): 4
Shape of Tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
def attributes(tensor):
  """
  Prints the attributes of the input tensor
  """
  print("Datatype of every element:", tensor.dtype)
  print("Number of Dimensions (rank):" ,tensor.ndim)
  print("Shape of Tensor:" , tensor.shape)
  print("Elements along the 0 axis:" , tensor.shape[0])
  print("Elements along the last axis:" , tensor.shape[-1])
  print("Total number of elements in our tensor:" , tf.size(tensor))

In [ ]:
attributes(r4_tensor)

Datatype of every element: <dtype: 'float32'>
Number of Dimensions (rank): 4
Shape of Tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


### Indexing Tensors

Tensors can be indexed just like python arrays

In [ ]:
# Get the first 2 elements of each dimension

r4_tensor[:2 , :2 ,:2 ,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one

r4_tensor[:1 ,:1 ,:1 ,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
r2_tensor = tf.ones(shape=(2,3))
r2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
r2_tensor.shape

TensorShape([2, 3])

In [ ]:
r2_tensor.ndim

2

In [ ]:
attributes(r2_tensor)

Datatype of every element: <dtype: 'float32'>
Number of Dimensions (rank): 2
Shape of Tensor: (2, 3)
Elements along the 0 axis: 2
Elements along the last axis: 3
Total number of elements in our tensor: tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
# Get the last item of each of row of our rank 2 tensor
r2_tensor[:,-2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [ ]:
#Add in extra dimension to our rank 2 tensor
r3_tensor = r2_tensor[...,tf.newaxis]
r3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(r2_tensor , axis = -1) # "-1" means final axis


<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tf.expand_dims(r2_tensor , axis =0) # expand the 0 axis "0" means adding in the front

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

### Manipulating tensors (tensor operations)

**Basic Operations**
* Addition
* Multiplication
* Division
* Subtraction

In [ ]:
tensor = tf.constant([[10 ,7] , [3 , 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Addition
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication
tensor*3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]], dtype=int32)>

In [ ]:
# Subtraction
tensor-2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [ ]:
# Division
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [ ]:
# We can use tensorflow buildt-in Functions
tf.multiply(tensor , 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

Matrix multiplication is commonly used methods in machine learning

In [ ]:
# Matrix multiplication in TensorFlow
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor , tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix Multiplication in python with "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
x = tf.constant([[1 , 2],
                 [3 , 4],
                 [9 ,10]])

y = tf.constant([[1 , 1],
                 [2 , 2],
                 [3 , 3]])

x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [ 3,  4],
        [ 9, 10]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2],
        [3, 3]], dtype=int32)>)

In [ ]:
# Reshaping a tensor
tf.reshape( y , shape =(3 ,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3]], dtype=int32)>

In [ ]:
x @ tf.reshape(y , shape =(2 ,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5,  7,  8],
       [11, 15, 18],
       [29, 39, 48]], dtype=int32)>

In [ ]:
# Transpose

tf.transpose(x).shape

TensorShape([2, 3])

In [ ]:
x.shape

TensorShape([3, 2])

**The Dot Product**

Matrix Multiplication is also known as Dot Product

performe using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
tf.matmul(x , tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  6,  9],
       [ 7, 14, 21],
       [19, 38, 57]], dtype=int32)>

In [ ]:
tf.matmul(x , tf.reshape( y , shape =(2 , 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5,  7,  8],
       [11, 15, 18],
       [29, 39, 48]], dtype=int32)>

In [ ]:
print("Normal Y:")
print(y ,"\n")

print("Y reshaped to (2,3):")
print(tf.transpose(y))

Normal Y:
tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul( x , tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  6,  9],
       [ 7, 14, 21],
       [19, 38, 57]], dtype=int32)>

Generally , when performing matrix multiplication we will perform transpose rather than reshape in one of the matrices

### Changing the data type of tensors

In [ ]:
# Create a new tensor with default datatype (float32)
b = tf.constant([1.7 , 7.4])
b.dtype

tf.float32

In [ ]:
c = tf.constant([2 , 3])
c.dtype

tf.int32

### Aggregating Tensors

Aggregating Tensors = condensing them from multiple values down to a smaller amount of values.





In [ ]:
# Getting the absolute values

d = tf.constant([-7 ,10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, 10], dtype=int32)>

In [ ]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of Aggregation:
* Minimum
* Maximum
* Get the mean of tensor
* Get the sum of tensor

In [ ]:
l  =tf.constant([7,23])
l

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 23], dtype=int32)>

In [ ]:
attributes(l)

Datatype of every element: <dtype: 'int32'>
Number of Dimensions (rank): 1
Shape of Tensor: (2,)
Elements along the 0 axis: 2
Elements along the last axis: 2
Total number of elements in our tensor: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
tf.size(l) , l.shape , l.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=2>, TensorShape([2]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(l)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Find the maximum
tf.reduce_max(l)

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [ ]:
# Find the mean
tf.reduce_mean(l)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
# Find the sum
tf.reduce_sum(l)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
# Find the variance

import tensorflow_probability as tfp

tfp.stats.variance(l)

<tf.Tensor: shape=(), dtype=int32, numpy=64>

In [ ]:
# Find the Standard Deviation
tf.math.reduce_std(tf.cast(l , dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

**Find the positional maximum and minimum**

In [ ]:
# Find the variance of tensor
tfp.stats.variance(l)

<tf.Tensor: shape=(), dtype=int32, numpy=64>

In [ ]:
# Second way of finding variance

tf.math.reduce_variance(tf.cast(l  , dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=64.0>

## Find the postional Maximum and Minimum

In [ ]:
tf.random.set_seed(42)

f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Positional Maximum ( arg max )
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index of largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Maximum value of f
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
f[tf.argmax(f)] == tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Postitional Minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using positional minimum index
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
g = tf.constant(tf.random.uniform( shape = [50]) , shape = (1 , 1, 1, 1, 50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
g_squeezed = tf.squeeze(g)

In [ ]:
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

In [ ]:
g_squeezed.shape

TensorShape([50])

### One-Hot Encoding in Tensors

In [ ]:
# Create a list of indices
some_list = [ 0 , 1 , 2 , 3]
# One-hot encode
tf.one_hot(some_list , depth = 4) # Depth is number of elements

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list , depth= 4 , on_value="CEO" , off_value="self made billionare")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'CEO', b'self made billionare', b'self made billionare',
        b'self made billionare'],
       [b'self made billionare', b'CEO', b'self made billionare',
        b'self made billionare'],
       [b'self made billionare', b'self made billionare', b'CEO',
        b'self made billionare'],
       [b'self made billionare', b'self made billionare',
        b'self made billionare', b'CEO']], dtype=object)>

In [ ]:
### Squaring , log , square root

In [ ]:
# Create a new tensor
h = tf.range(1 ,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root (Requires non-int type)
tf.math.sqrt(tf.cast(h , dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Find the log value
tf.math.log(tf.cast(h, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [ ]:
j = tf.constant(np.array([3. , 7. , 10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor to numpy array
np.array(j) , type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)